spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/com_db?currentSchema=public
    username: postgres
    password: admin
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        default_schema: public
    database: postgresql
  data:
    redis:
      host: localhost # Адрес вашего Redis-сервера
      port: 6379
      # password:
      # database: 0

resilience4j:
  ratelimiter:
    instances:
      accountCreation: # <- Это имя, на которое ссылается аннотация
        limit-for-period: 3    # Количество запросов <- параметр LIMIT
        limit-refresh-period: 1h # Период обновления <- параметр DURATION
        timeout-duration: 0     # Время ожидания (0 = сразу исключение)

server:
  port: 8080
  url: "http://localhost:8080"
